export const publicOptions = [
    { value: 'Geral', label: 'Geral' },
    { value: 'Agricultores', label: 'Agricultores' },
    { value: 'Atletas', label: 'Atletas' },
    { value: 'Bebês', label: 'Bebês' },
    { value: 'Desenvolvedores de software', label: 'Desenvolvedores de software' },
    { value: 'Estudantes', label: 'Estudantes' },
    { value: 'Empresas', label: 'Empresas' },
    { value: 'Investidores', label: 'Investidores' },
    { value: 'Líderes', label: 'Líderes' },
    { value: 'Motoristas', label: 'Motoristas' },
    { value: 'Músicos', label: 'Músicos' },
    { value: 'Pets', label: 'Pets' },
    { value: 'Restaurantes', label: 'Restaurantes' },
    { value: 'Turistas', label: 'Turistas' }
  ]
  
export const nicheOptions = [
    { value: 'Agropecuária', label: 'Agropecuária' },
    { value: 'Artesanato', label: 'Artesanato' },
    { value: 'Astronomia', label: 'Astronomia' },
    { value: 'Aplicativos', label: 'Aplicativos' },
    { value: 'Bebidas', label: 'Bebidas' },
    { value: 'Beleza e cosméticos', label: 'Beleza e cosméticos' },
    { value: 'Blogs', label: 'Blogs' },
    { value: 'Ciência e tecnolgia', label: 'Ciência e tecnologia' },
    { value: 'Cinema', label: 'Cinema' },
    { value: 'Criptomoedas', label: 'Criptomoedas' },
    { value: 'Decoração', label: 'Decoração' },
    { value: 'Educação', label: 'Educação' },
    { value: 'Energia solar', label: 'Energia solar' },
    { value: 'Entretenimento', label: 'Entretenimento' },
    { value: 'Eletrônicos', label: 'Eletrônicos' },
    { value: 'Esportes', label: 'Esportes' },
    { value: 'Exchange de criptomoedas', label: 'Exchange de criptomoedas' },
    { value: 'e-Sports', label: 'e-Sports' },
    { value: 'Finanças', label: 'Finanças' },
    { value: 'Freelances', label: 'Freelances' },
    { value: 'Gadgets', label: 'Gadgets' },
    { value: 'Imóveis', label: 'Imóveis' },
    { value: 'Inteligência Artificial', label: 'Inteligência Artificial' },
    { value: 'Instituição Financeira', label: 'Instituição Financeira' },
    { value: 'Investimentos', label: 'Investimentos' },
    { value: 'Jardinagem', label: 'Jardinagem' },
    { value: 'Livros', label: 'Livros' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Moda', label: 'Moda' },
    { value: 'Música', label: 'Música' },
    { value: 'Negócios', label: 'Negócios' },
    { value: 'Pets', label: 'Pets' },
    { value: 'Pousadas e hotelaria', label: 'Pousadas e hotelaria' },
    { value: 'Realidade Aumentada', label: 'Realidade Aumentada' },
    { value: 'Redes sociais', label: 'Redes sociais' },
    { value: 'Relacionamentos', label: 'Relacionamentos' },
    { value: 'Robôs', label: 'Robôs' },
    { value: 'Saúde', label: 'Saúde' },
    { value: 'Tecnologia em geral', label: 'Tecnologia em geral' },
    { value: 'Veículos', label: 'Veículos' },
    { value: 'Veículos elétricos', label: 'Veículos elétricos' },
    { value: 'Viagens', label: 'Viagens' },
    { value: 'Outros', label: 'Outros' },
  
  ]